### ISSUE TITLE
How do I run the fine-tuned model?

### ISSUE THREAD

**Issue by vincentabraham** [geronimi73/qlora-minimal#1]
Hi, I trained the Llama-2-7b-chat model on my customised dataset with the steps you mentioned in qlora-minimal.ipynb. I had also saved the model with 
`
trainer.model.save_pretrained(new_model)
trainer.tokenizer.save_pretrained(new_model)
`

But I can't find any code on how do I run the fine-tuned model. Could you help me with this?

**Comment by geronimi73** [comment]
like this for example:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

modelpath="path_to_your_model"

model = AutoModelForCausalLM.from_pretrained(
    modelpath,    
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained(modelpath) 

messages = [
    {"role": "user", "content": "hello"},
]
        
input_tokens = tokenizer.apply_chat_template(
    messages, 
    add_generation_prompt=True,
    return_tensors="pt"
).to("cuda")
output_tokens = model.generate(input_tokens, max_new_tokens=500)
output = tokenizer.decode(output_tokens[0])

print(output)
```

**Comment by vincentabraham** [comment]
Thanks. This works. Also is there any way to gain insights from the model. For example, if I'm fine-tuning it for a binary classification problem, which words specifically influenced the model's decision?

**Comment by geronimi73** [comment]
> if I'm fine-tuning it for a binary classification problem, which words specifically influenced the model's decision?

hm not that I know of

**Comment by vincentabraham** [comment]
Thanks for the help
